apiVersion: V1
kind: Service
metadata: 
  name: starbux0-svc
spec:    
   type: loadbalencer
   selector:  
      app: nginx:stable-alpine3.23-perl
   ports: 
   - port:  80
     targetPorts: 80
      



